### ISSUE TITLE
SOQL: Lookup fields cause error

### ISSUE THREAD

**Issue by aheber** [g8rswimmer/go-sfdc#39]
Running a SOQL query like "SELECT Id, AccountId, Account.Name FROM Contact" causes an error because the processor sees a nested object and thinks it is a nested list of results caused by querying from a top-down lookup where this is a bottom-up lookup and errors with `SOQL Query Error query response: done is not present`

Remembering that these can actually be nested up to five levels.

I'm not familiar enough with the package yet to know if I'm doing something wrong. Problem appears to be generally located in the assumptions held that if it isn't an `attributes` key then it must be a nested query.

soql\record.go--newQueryRecord:19
`if k != sfdc.RecordAttributes  {`

Returned data is in the form
``` JSON
{
    "totalSize": 1,
    "done": true,
    "records": [
        {
            "attributes": {
                "type": "Contact",
                "url": "/services/data/v45.0/sobjects/Contact/003XXXXXXXXXXXXXXX"
            },
            "Id": "003XXXXXXXXXXXXXXX",
            "AccountId": "001XXXXXXXXXXXXXXX",
            "Account": {
                "attributes": {
                    "type": "Account",
                    "url": "/services/data/v45.0/sobjects/Account/001XXXXXXXXXXXXXXX"
                },
                "Name": "Test Account"
            }
        }
    ]
}
```

I'll try and figure it out and get a PR submitted.

**Comment by g8rswimmer** [comment]
@aheber 
Thanks for providing a PR on this issue.  However, the changes in the PR do not really fit into the framework.  The record in the `sfdc` package should not _know_ about the `records` in the json map.

The approach that I took with this issue, is to treat it as Salesforce API treated it, like another record.  From that, I added the loop up, which is another record.  This allows for a consistent record type and access the fields are the same.  This will also handle the nested values as it calls the `RecordFromJSONMap` for each nested object.

Also, I am not a huge fan of swallowing errors.

**Comment by g8rswimmer** [comment]
the new release v2.0 will address this issue.

**Comment by aheber** [comment]
@g8rswimmer I had a chance to try the new implementation, I don't think it works very well.

Salesforce allows you to create multiple lookups to the same SObject type. Your implementation maps by the SObject type and not by the relationship name (`r.lookUps[rec.sobject] = rec`). If we have multiple relationships to the same SObject then only one of them is preserved as the later will overwrite the place in the lookup map.

`SELECT Id, Name, LastModifiedBy.Name, CreatedBy.Name FROM Account`

Which returns a response like
```
{
    "totalSize": 139,
    "done": true,
    "records": [
        {
            "attributes": {
                "type": "Account",
                "url": "/services/data/v46.0/sobjects/Account/0010x00000ksXXXXXX"
            },
            "Id": "0010x00000ksXXXXXX",
            "Name": "Test User Account",
            "LastModifiedBy": {
                "attributes": {
                    "type": "User",
                    "url": "/services/data/v46.0/sobjects/User/0050x0000032XXXXXX"
                },
                "Name": "User User"
            },
            "CreatedBy": {
                "attributes": {
                    "type": "User",
                    "url": "/services/data/v46.0/sobjects/User/0050x0000032XXXXXX"
                },
                "Name": "User User"
            }
        }
    ]
}
```

You can see that "User" is the type for both relationships in this query. It would be more appropriate and traditional to hold the reference map the same way that the query addressed it, by the relationship name, `LastModifiedBy` and `CreatedBy` in this case.

If these were custom fields they would have names like `Inside_Sales_Rep__r` or `Executive_Sponsor__r` and the record IDs for the lookup would be held in `Inside_Sales_Rep__c` and `Executive_Sponsor__c` fields directly on the base object.
