### ISSUE TITLE
Not able to use the result.Next to paginate through more records

### ISSUE THREAD

**Issue by criswit** [g8rswimmer/go-sfdc#53]
Hi g8rswimmer,

first off - love your repo. i'm experiementing trying to use the "Next" function of the query result and can't get past a nil pointer dereference. 

Do you have any sample code that i could quickly look out that demonstrates how to paginate through a large query REsult?

Thanks!

**Comment by g8rswimmer** [comment]
Would you be able to paste some code and also the panic trace.  I am wondering what is causing the nil pointer panic.

**Comment by criswit** [comment]
Sorry for delay - I figured this out. Was a problem on my end
